---
# This playbook installs gitkraken - lovely git UI manager
# unfortunately there're no fedora / rhel packages so
# we download zip, unzip it and add gnome3 launcher entry + gitkraken icon
# in order to update your current installation you have to remove it manually
# or invoke playbook with "-e update_apps=true"

- name: Check if there is any old installation
  stat: path="{{ local_soft_dir }}/gitkraken"
  register: gitkraken_state

- block:
  - name: Download package
    get_url: >
      dest={{ temp_dir }}/gitkraken.tar.gz
      url="https://release.gitkraken.com/linux/gitkraken-amd64.tar.gz"

  - name: Ensure GitKraken directory is removed
    file: >
      path={{ local_soft_dir }}/GitKraken
      state=absent

  - name: Extract archive
    unarchive: >
      src={{ temp_dir }}/gitkraken.tar.gz
      dest={{ local_soft_dir }}/
      group={{ group }}
      owner={{ user }}

  - name: Copy gitkraken logo
    copy: >
      src=gitkraken.jpg
      dest={{ local_soft_dir }}/GitKraken/gitkraken.jpg
      owner={{ user }}
      group={{ group }}

  - name: Create desktop entry for Gnome3
    template: >
      src=gitkraken.desktop.j2
      dest={{ home_dir }}/.local/share/applications/GitKraken.desktop
      owner={{ user }}
      group={{ group }}
      mode=0700

  when: gitkraken_state.stat.exists == false or update_apps | default('') != ''